site_name: Ingo Fruend
theme:
  name: material
  features:
    - navigation.sections
  custom_dir: overrides
plugins:
  - offline
  - blog:
      blog_dir: ./
      authors_file: authors.yml
  - search
  - tags
nav:
  - index.md
  - about.md
