site_name: Ingo Fruend
theme:
  name: material
  features:
    - navigation.sections
  custom_dir: overrides
  palette:
    primary: white
    accent: cyan
  font:
    text:
      PT Serif
      # Libre Baskerville
  logo: images/logo.png
plugins:
  - offline
  - blog:
      blog_dir: ./
      authors_file: authors.yml
  - search
  - tags
nav:
  - index.md
  - about.md
