name: Upload
on:
  push:
    branches: ["master"]

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.lock

      - name: Build 
        run: mkdocs build

      - name: Upload
        uses: Dylan700/sftp-upload-action@latest
        with:
          # Server as ftp.example.com
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 23
          uploads: |
          site/ => /
